version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    hostname: flask
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "81:5000"
    restart: always
    privileged: true


  redis:
    image: redis
    container_name: redis
    hostname: redis
    environment:
      TZ: "America/Sao_Paulo"
    restart: always
    privileged: true

